### ISSUE TITLE
Firebug 'undefined' error

### ISSUE THREAD

**Issue by mariamichou** [VisualDataWeb/webprotege#13]
Probably webvowl.modules.focuser needs tweaking. 
When an element is selected, its state is focused. When the same element is again selected, Firebug generates 'undefined' error. 
This is a default config in the original app, but here we need it to be changed.
Something that has to do with focuser.reset function maybe?

**Comment by linkvt** [comment]
Hello Maria, it is intended, that selecting an already selected element removes the selection. Because there isn't a selected element now, the module tells it is undefined.

I'm currently not 100% sure where the problem occurs for you, can you tell me when this error occurs for you?

**Comment by mariamichou** [comment]
Hello, I know it's a design feature in your app. However, in webprotege, when one selects an already selected element, I (try to) render details for an element, now, undefined. So, maybe I should handle this as a feature as well and "clear" the Selection Details panel, as you implemented it.

**Comment by linkvt** [comment]
Ah ok now I understand I think. You can also just check whether the JSO is null. If it is, just leave the method, otherwise update the details.

**Comment by mariamichou** [comment]
Yes that's the idea. Thanks!
